import type { Metadata } from "next";
import { Header } from "@/components/shared/header";

import type { Viewport } from 'next'
import { Suspense } from "react";

export const viewport: Viewport = {
    themeColor: 'black',
}

export const metadata: Metadata = {
    title: "Next Pizza | Главная",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <main className="min-h-screen">
            <Suspense>
                <Header />
            </Suspense>
            {children}
            {modal}
        </main>
    );
}
