import type { Metadata } from "next";
import { Header } from "@/components/shared/header";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Next Pizza | Корина",
    description: "Generated by create next app",
};

export default function CheckoutLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <main className="min-h-screen bg-[#F4F1EE]">
            <Suspense>
                <Header hasCart={false} hasSearch={false} />
            </Suspense>
            {children}
        </main>
    );
}
